services:
  backend:
    build:
      context: ./backend/Chatalyst
      dockerfile: Dockerfile
    container_name: spring-backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
