spring:
  application:
    name: chatanalys

  ai:
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always

    vectorstore:
      pgvector:
        schema-name: public
        initialize-schema: true
        dimensions: 768

    mistral:
      api-key: ${MISTRAL_API_KEY}
      chat:
        options:
          model: mistral-tiny

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_DATABASE}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  jackson:
    serialization:
      write-dates-as-timestamps: false

server:
  port: 8500